# DATASET GLOBAL

#### Adding paths

In [1]:
import sys
sys.path.append('../')
sys.path.append('../Scripts/')

### Libraries

In [2]:
import collections
import json
from Global_Variables import *
import Aux_Functions as af
import numpy as np
import pandas as pd

In [3]:
# Hardcode for test
genotype = "1b"

### Open fasta file & Acession Number e Sequence

In [4]:
Datasets_Reference = [("NS5A_1b_06.03.2018.aln","1b"),
                     ("NS5A_GEN1a_02.05.16","1a"),
                     ("NS5A_GEN3_05.05.16","3")]

In [5]:
genotype_1b = af.fasta_to_dict("../Data/" + "NS5A_1b_06.03.2018.aln")
genotype_1b_codons = {}
for sequence in genotype_1b.items():
    genotype_1b_codons[sequence[0]] = af.sequence_codons(sequence[1])

#### Contar as frequÃªncias

In [6]:
df = pd.DataFrame(data=genotype_1b_codons)
df = df.transpose()
df_frequency = df.apply(pd.value_counts)
df_frequency = df_frequency.apply(lambda x: x/len(df))

In [7]:
df_frequency

,24,28,29,30,31,32,54,58,92,93
AAA,NaN,NaN,NaN,0.002427,NaN,NaN,NaN,NaN,NaN,NaN
AAC,NaN,NaN,NaN,NaN,NaN,NaN,0.008495,NaN,NaN,NaN
AAG,0.009709,NaN,NaN,0.001214,NaN,NaN,NaN,NaN,NaN,NaN
AAT,NaN,NaN,NaN,NaN,NaN,NaN,0.038835,NaN,NaN,NaN
ACA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.009709,0.004854,NaN
ACG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001214,0.008495,NaN
ACT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001214,NaN,NaN
AGG,NaN,NaN,NaN,0.004854,NaN,NaN,NaN,NaN,NaN,NaN
ATA,NaN,NaN,NaN,NaN,0.002427,NaN,NaN,NaN,NaN,NaN
ATG,NaN,0.016990,NaN,0.001214,0.033981,NaN,NaN,NaN,NaN,NaN
CAA,0.067961,NaN,NaN,0.003641,NaN,NaN,0.410194,0.002427,NaN,NaN
CAC,NaN,NaN,NaN,NaN,NaN,NaN,0.156553,NaN,NaN,0.037621
CAG,0.915049,NaN,NaN,0.037621,NaN,NaN,0.252427,NaN,NaN,NaN
CAR,NaN,NaN,NaN,NaN,NaN,NaN,0.002427,NaN,NaN,NaN
CAT,NaN,NaN,NaN,NaN,NaN,NaN,0.108010,NaN,NaN,NaN
CCA,NaN,NaN,0.167476,NaN,0.001214,0.094660,NaN,0.830097,NaN,NaN
CCC,NaN,NaN,0.004854,NaN,NaN,0.013350,NaN,0.014563,NaN,NaN
CCG,NaN,0.001214,0.822816,NaN,NaN,0.888350,NaN,0.089806,NaN,NaN
CCT,NaN,NaN,0.003641,NaN,NaN,0.003641,NaN,0.004854,NaN,NaN
CGA,0.001214,NaN,NaN,0.131068,NaN,NaN,NaN,NaN,NaN,NaN
CGC,NaN,NaN,NaN,0.004854,NaN,NaN,NaN,NaN,NaN,NaN
CGG,0.006068,NaN,NaN,0.810680,NaN,NaN,NaN,NaN,NaN,NaN
CGT,NaN,NaN,NaN,0.002427,NaN,NaN,NaN,NaN,NaN,NaN
CTA,NaN,0.018204,NaN,NaN,0.086165,NaN,0.003641,0.006068,NaN,NaN
CTC,NaN,0.007282,NaN,NaN,0.001214,NaN,0.001214,NaN,NaN,NaN
CTG,NaN,0.927184,NaN,NaN,0.110437,NaN,NaN,0.001214,NaN,NaN
CTT,NaN,0.002427,NaN,NaN,0.003641,NaN,NaN,NaN,NaN,NaN
GAA,NaN,NaN,NaN,NaN,NaN,NaN,0.001214,NaN,NaN,NaN
GCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004854,0.570388,NaN
GCC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003641,NaN
GCG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.393204,NaN
GCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.010922,NaN
GGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.002427,NaN
GTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001214,NaN
GTG,NaN,0.003641,NaN,NaN,NaN,NaN,NaN,NaN,0.003641,NaN
TAC,NaN,NaN,NaN,NaN,NaN,NaN,0.006068,NaN,NaN,0.945388
TAT,NaN,NaN,NaN,NaN,NaN,NaN,0.009709,NaN,NaN,0.015777
TCA,NaN,NaN,0.001214,NaN,NaN,NaN,NaN,0.031553,0.001214,NaN
TCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001214,NaN,NaN
TGC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.001214
TTA,NaN,NaN,NaN,NaN,0.445388,NaN,0.001214,0.001214,NaN,NaN
TTG,NaN,0.023058,NaN,NaN,0.315534,NaN,NaN,NaN,NaN,NaN

#### Tabela

In [8]:
df_codons = pd.DataFrame(columns=["Genotype", "Position", "Codon", "Frequency"])

In [9]:
for position in df_frequency.columns:
    for codon in df_frequency.index:
        new_row = [genotype, position, codon, df_frequency.at[codon,position]]
        new_series = pd.Series(new_row, index = df_codons.columns)
        df_codons = df_codons.append(new_series, ignore_index=True)

In [11]:
df_codons = df_codons.fillna(0) # Not a Number values into 0

In [12]:
df_codons

    Genotype  Position Codon  Frequency
0         1b        24   AAA   0.000000
1         1b        24   AAC   0.000000
2         1b        24   AAG   0.009709
3         1b        24   AAT   0.000000
4         1b        24   ACA   0.000000
5         1b        24   ACG   0.000000
6         1b        24   ACT   0.000000
7         1b        24   AGG   0.000000
8         1b        24   ATA   0.000000
9         1b        24   ATG   0.000000
10        1b        24   CAA   0.067961
11        1b        24   CAC   0.000000
12        1b        24   CAG   0.915049
13        1b        24   CAR   0.000000
14        1b        24   CAT   0.000000
15        1b        24   CCA   0.000000
16        1b        24   CCC   0.000000
17        1b        24   CCG   0.000000
18        1b        24   CCT   0.000000
19        1b        24   CGA   0.001214
20        1b        24   CGC   0.000000
21        1b        24   CGG   0.006068
22        1b        24   CGT   0.000000
23        1b        24   CTA   0.000000
24        1b        24   CTC   0.000000
25        1b        24   CTG   0.000000
26        1b        24   CTT   0.000000
27        1b        24   GAA   0.000000
28        1b        24   GCA   0.000000
29        1b        24   GCC   0.000000
..       ...       ...   ...        ...
390       1b        93   CAG   0.000000
391       1b        93   CAR   0.000000
392       1b        93   CAT   0.000000
393       1b        93   CCA   0.000000
394       1b        93   CCC   0.000000
395       1b        93   CCG   0.000000
396       1b        93   CCT   0.000000
397       1b        93   CGA   0.000000
398       1b        93   CGC   0.000000
399       1b        93   CGG   0.000000
400       1b        93   CGT   0.000000
401       1b        93   CTA   0.000000
402       1b        93   CTC   0.000000
403       1b        93   CTG   0.000000
404       1b        93   CTT   0.000000
405       1b        93   GAA   0.000000
406       1b        93   GCA   0.000000
407       1b        93   GCC   0.000000
408       1b        93   GCG   0.000000
409       1b        93   GCT   0.000000
410       1b        93   GGA   0.000000
411       1b        93   GTA   0.000000
412       1b        93   GTG   0.000000
413       1b        93   TAC   0.945388
414       1b        93   TAT   0.015777
415       1b        93   TCA   0.000000
416       1b        93   TCT   0.000000
417       1b        93   TGC   0.001214
418       1b        93   TTA   0.000000
419       1b        93   TTG   0.000000

[420 rows x 4 columns]

In [13]:
df_codon_usage = pd.read_csv("../Data/Codon_Usage_G1.csv", sep=";")

In [14]:
df_codon_usage

   Codon  HCV-G1
0    GCG    0.23
1    GCA    0.17
2    GCT    0.20
3    GCC    0.40
4    TGT    0.31
5    TGC    0.69
6    GAT    0.28
7    GAC    0.72
8    GAG    0.72
9    GAA    0.28
10   TTT    0.36
11   TTC    0.64
12   GGG    0.29
13   GGA    0.14
14   GGT    0.16
15   GGC    0.41
16   CAT    0.43
17   CAC    0.57
18   ATA    0.25
19   ATT    0.18
20   ATC    0.56
21   AAG    0.68
22   AAA    0.32
23   TTG    0.12
24   TTA    0.03
25   CTG    0.32
26   CTA    0.07
27   CTT    0.17
28   CTC    0.29
29   ATG    1.00
..   ...     ...
34   CCT    0.27
35   CCC    0.40
36   CAG    0.59
37   CAA    0.41
38   AGG    0.30
39   AGA    0.14
40   CGG    0.19
41   CGA    0.07
42   CGT    0.08
43   CGC    0.21
44   AGT    0.07
45   AGC    0.23
46   TCG    0.12
47   TCA    0.13
48   TCT    0.13
49   TCC    0.33
50   ACG    0.23
51   ACA    0.15
52   ACT    0.20
53   ACC    0.41
54   GTG    0.41
55   GTA    0.10
56   GTT    0.15
57   GTC    0.34
58   TGG    1.00
59   TAT    0.30
60   TAC    0.70
61   TGA    1.00
62   TAG    0.00
63   TAA    0.00

[64 rows x 2 columns]

Join entre df_codon e df_codon_usage utilizando como chave a coluna "Codon"

In [15]:
df_join = pd.merge(df_codons, df_codon_usage, on=['Codon'])

In [16]:
df_join.head(100)

   Genotype  Position Codon  Frequency  HCV-G1
0        1b        24   AAA   0.000000    0.32
1        1b        28   AAA   0.000000    0.32
2        1b        29   AAA   0.000000    0.32
3        1b        30   AAA   0.002427    0.32
4        1b        31   AAA   0.000000    0.32
5        1b        32   AAA   0.000000    0.32
6        1b        54   AAA   0.000000    0.32
7        1b        58   AAA   0.000000    0.32
8        1b        92   AAA   0.000000    0.32
9        1b        93   AAA   0.000000    0.32
10       1b        24   AAC   0.000000    0.71
11       1b        28   AAC   0.000000    0.71
12       1b        29   AAC   0.000000    0.71
13       1b        30   AAC   0.000000    0.71
14       1b        31   AAC   0.000000    0.71
15       1b        32   AAC   0.000000    0.71
16       1b        54   AAC   0.008495    0.71
17       1b        58   AAC   0.000000    0.71
18       1b        92   AAC   0.000000    0.71
19       1b        93   AAC   0.000000    0.71
20       1b        24   AAG   0.009709    0.68
21       1b        28   AAG   0.000000    0.68
22       1b        29   AAG   0.000000    0.68
23       1b        30   AAG   0.001214    0.68
24       1b        31   AAG   0.000000    0.68
25       1b        32   AAG   0.000000    0.68
26       1b        54   AAG   0.000000    0.68
27       1b        58   AAG   0.000000    0.68
28       1b        92   AAG   0.000000    0.68
29       1b        93   AAG   0.000000    0.68
..      ...       ...   ...        ...     ...
70       1b        24   AGG   0.000000    0.30
71       1b        28   AGG   0.000000    0.30
72       1b        29   AGG   0.000000    0.30
73       1b        30   AGG   0.004854    0.30
74       1b        31   AGG   0.000000    0.30
75       1b        32   AGG   0.000000    0.30
76       1b        54   AGG   0.000000    0.30
77       1b        58   AGG   0.000000    0.30
78       1b        92   AGG   0.000000    0.30
79       1b        93   AGG   0.000000    0.30
80       1b        24   ATA   0.000000    0.25
81       1b        28   ATA   0.000000    0.25
82       1b        29   ATA   0.000000    0.25
83       1b        30   ATA   0.000000    0.25
84       1b        31   ATA   0.002427    0.25
85       1b        32   ATA   0.000000    0.25
86       1b        54   ATA   0.000000    0.25
87       1b        58   ATA   0.000000    0.25
88       1b        92   ATA   0.000000    0.25
89       1b        93   ATA   0.000000    0.25
90       1b        24   ATG   0.000000    1.00
91       1b        28   ATG   0.016990    1.00
92       1b        29   ATG   0.000000    1.00
93       1b        30   ATG   0.001214    1.00
94       1b        31   ATG   0.033981    1.00
95       1b        32   ATG   0.000000    1.00
96       1b        54   ATG   0.000000    1.00
97       1b        58   ATG   0.000000    1.00
98       1b        92   ATG   0.000000    1.00
99       1b        93   ATG   0.000000    1.00

[100 rows x 5 columns]

In [19]:
df_join.to_csv("../Outputs/CodonUsage_Frequency.csv", sep=";", index=False)